# Generated by Django 6.1.1 on 2026-09-09 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Landlord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(help_text='Contact phone number, e.g. 08012345678.', max_length=20)),
                ('verified', models.BooleanField(default=False, help_text='Whether the landlord identity has been verified.')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_joined'],
            },
        ),
    ]
