import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { ListingCard } from "../components/ListingCard";
import { listingApi } from "../services/api";

export function RecommendationPage() {
  const [form, setForm] = useState({ budget: "300000", max_distance: "3", electricity: "24hr", water: "borehole", internet: "true" });
  const [submitted, setSubmitted] = useState(form);
  const query = useQuery({ queryKey: ["recommendations", submitted], queryFn: () => listingApi.recommendation(submitted) });
  const results = query.data?.results || [];
  return <div className="space-y-8"><div className="max-w-2xl"><p className="mb-3 text-xs font-bold uppercase tracking-[.16em] text-coral">Personalised for your routine</p><h1 className="font-display text-5xl font-bold leading-none md:text-6xl">Best for <em className="text-coral">you.</em></h1><p className="mt-4 text-muted">Tell us what matters around LASU Epe and our transparent scoring will rank the strongest matches.</p></div><form onSubmit={(event) => { event.preventDefault(); setSubmitted(form); }} className="grid gap-4 border border-line bg-cream p-5 md:grid-cols-5"><label className="grid gap-2 text-xs text-muted">Budget<input type="number" value={form.budget} onChange={(event) => setForm({ ...form, budget: event.target.value })} className="border border-line p-2.5 text-ink" /></label><label className="grid gap-2 text-xs text-muted">Max km<input type="number" value={form.max_distance} onChange={(event) => setForm({ ...form, max_distance: event.target.value })} className="border border-line p-2.5 text-ink" /></label><label className="grid gap-2 text-xs text-muted">Power<select value={form.electricity} onChange={(event) => setForm({ ...form, electricity: event.target.value })} className="border border-line p-2.5 text-ink"><option value="">Any</option><option value="24hr">24 hours</option><option value="rationed">Rationed</option></select></label><label className="grid gap-2 text-xs text-muted">Water<select value={form.water} onChange={(event) => setForm({ ...form, water: event.target.value })} className="border border-line p-2.5 text-ink"><option value="">Any</option><option value="borehole">Borehole</option><option value="pipe_borne">Pipe-borne</option></select></label><button className="self-end bg-ink px-4 py-3 text-sm font-bold text-white">Find my matches →</button></form>{query.isLoading && <p className="text-muted">Scoring homes around campus…</p>}{query.isError && <p className="border border-[#e9b8a8] bg-[#fff1ec] p-4 text-[#86402f]">{query.error.message}</p>}<div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{results.map((result) => <ListingCard key={result.listing.id} listing={result.listing} score={result.score} />)}</div></div>;
}
